name: Extract HLS from YouTube JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # runs hourly

jobs:
  extract-hls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Run HLS Extractor Script
        run: python scripts/extract_hls.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add channel_responses/ channels.m3u
          git commit -m "Update channel responses and playlist" || echo "No changes to commit"
          git push
