name: Extract HLS from YouTube JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # runs hourly

jobs:
  extract-hls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Run HLS Extractor Script
        run: python scripts/extract_hls.py

      - name: Commit and Push Changes
        env:
            TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add channels.m3u .gitignore
          git commit -m "Update playlist" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
    
